#!/usr/bin/env node
/**
 * Pull `38 · A Letter From Week XII`'s prose out of the frame.
 *
 * The previous bundle assembled this letter from the questionnaire's answers;
 * this one writes it out in full, so the words are the design's and only the
 * name is his. Twelve paragraphs, `<p>` by `<p>`, in document order.
 *
 * Writes `src/content/weekXiiLetter.ts`.
 */
import fs from 'node:fs';
const { frames } = JSON.parse(fs.readFileSync('.uifinal1/scenes/Email-Login.json', 'utf8'));
const f = frames.find((x) => x.label === 'Letter Week XII');
const paras = [];
for (let i = 0; i < f.nodes.length; i++) {
  if (f.nodes[i].tag !== 'p') continue;
  let t = '';
  for (let j = i + 1; j < f.nodes.length && f.nodes[j].tag === '#text'; j++) t += f.nodes[j].text;
  paras.push(t);
}
const out = [
  '/**',
  ' * `38 · A Letter From Week XII` — the letter, word for word off the frame.',
  ' *',
  ' * GENERATED by `scripts/uifinal1/gen-letter.mjs`. The previous bundle built this',
  ' * letter out of the answers; this one writes it. Only the name is his.',
  ' */',
  'export const WEEK_XII_LETTER: string[] = [',
  ...paras.map((p) => '  ' + JSON.stringify(p) + ','),
  '];',
  '',
].join('\n');
fs.writeFileSync('src/content/weekXiiLetter.ts', out);
console.log(`src/content/weekXiiLetter.ts — ${paras.length} paragraphs`);
