#!/usr/bin/env node
/**
 * Generate the onboarding tail's data from the canvas frames.
 *
 * The tail's screens are drawings, not layouts: a 30-cell month, a 365-cell
 * year, an eleven-star night, a seven-bar week, a 240pt ring gauge with 48 tick
 * marks, and an ELO bell curve sampled at 61 points. Each is transcribed here
 * rather than re-derived, so the app draws the canvas's own geometry.
 *
 * Writes `src/content/onboardingTail.ts`.
 */
import fs from 'node:fs';

const { frames, source } = JSON.parse(fs.readFileSync('.uifinal1/scenes/Email-Login.json', 'utf8'));
const F = (l) => { const f = frames.find((x) => x.label === l); if (!f) throw new Error('no frame ' + l); return f; };
const num = (v) => Number(String(v).replace(/px|%/g, ''));

/** The dark cells of a grid of squares, in document order. */
function cells(label, match) {
  const f = F(label);
  const out = [];
  for (const n of f.nodes) {
    if (n.tag !== 'div' || !n.css) continue;
    if (!match(n.css)) continue;
    out.push(n.css.background === '#131313');
  }
  return out;
}

const cost30 = cells('Cost Next 30', (c) => c['aspect-ratio'] === '1' && c['border-radius'] === '10px');
const cost365 = cells('Cost Next 365', (c) => c['border-radius'] === '5px' && (c.background === '#131313' || c.background === '#FFFFFF'));

/** `30 · If Nothing Changes` paints its stars as eleven 1.3px radial gradients. */
const age80Stars = (() => {
  const f = F('Cost By Age 80');
  const layer = f.nodes.find((n) => n.css && /radial-gradient\(circle 1\.3px/.test(n.css['background-image'] ?? ''));
  return [...layer.css['background-image'].matchAll(/circle 1\.3px at (\d+)px (\d+)px/g)].map((m) => [Number(m[1]), Number(m[2])]);
})();

/** `26 · The Window to Protect` — seven bars and their day labels. */
const windowBars = (() => {
  const f = F('Results Pattern');
  const bars = f.nodes.filter((n) => n.css && n.css.flex === '1' && n.css['border-radius'] === '6px 6px 2px 2px');
  const labels = [];
  for (let i = 0; i < f.nodes.length; i++) {
    const n = f.nodes[i];
    if (n.css && n.css.flex === '1' && n.css['text-align'] === 'center' && n.css['font-size'] === '11.5px') {
      const t = f.nodes[i + 1];
      if (t && t.tag === '#text') labels.push(t.text);
    }
  }
  return bars.map((b, i) => ({ h: num(b.css.height), on: b.css.background === '#131313', label: labels[i] }));
})();

/** `27 · Your Starting Point` — the ring's ticks and the ELO curve's samples. */
const score = (() => {
  const f = F('Starting Score');
  const ticks = f.nodes
    .filter((n) => n.tag === 'line' && n.attrs && n.attrs.stroke === '#DDDAD2')
    .map((n) => [Number(n.attrs.x1), Number(n.attrs.y1), Number(n.attrs.x2), Number(n.attrs.y2)]);
  const arc = f.nodes.find((n) => n.tag === 'circle' && n.attrs && n.attrs['stroke-dasharray']);
  const curvePath = f.nodes.find((n) => n.tag === 'path' && n.attrs && n.attrs.stroke === '#D8D5CE');
  const pts = [...curvePath.attrs.d.matchAll(/([\d.]+),([\d.]+)/g)].map((m) => [Number(m[1]), Number(m[2])]);
  const marker = f.nodes.find((n) => n.tag === 'line' && n.attrs && n.attrs['stroke-width'] === '1.8');
  return {
    ticks,
    trackR: 104,
    strokeW: 10,
    circumference: Number(arc.attrs['stroke-dasharray'].split(' ')[1]) + Number(arc.attrs['stroke-dasharray'].split(' ')[0]),
    sampleDash: Number(arc.attrs['stroke-dasharray'].split(' ')[0]),
    curve: pts,
    sampleMarkerX: Number(marker.attrs.x1),
  };
})();

const j = (v) => JSON.stringify(v);
const out = [];
out.push('/**');
out.push(' * The onboarding tail\'s drawings, read off the canvas.');
out.push(' *');
out.push(' * GENERATED by `scripts/uifinal1/gen-tail.mjs` from');
out.push(` * \`${source}\`. Do not edit by hand — re-run the generator.`);
out.push(' */');
out.push('');
out.push('/** `28 · The Next 30 Days` — 30 cells, 6 across; true is a day that ends the same way. */');
out.push(`export const COST_30: boolean[] = ${j(cost30)};`);
out.push('');
out.push('/** `29 · One Year From Now` — 365 cells, 15 across. */');
out.push(`export const COST_365: boolean[] = ${j(cost365)};`);
out.push('');
out.push('/** `30 · If Nothing Changes` — eleven 1.3pt stars on #060606, at the frame\'s own points. */');
out.push(`export const AGE_80_STARS: [number, number][] = ${j(age80Stars)};`);
out.push('');
out.push('/** `26 · The Window to Protect` — seven bars, their heights in points, and their labels. */');
out.push(`export const WINDOW_BARS: { h: number; on: boolean; label: string }[] = ${j(windowBars)};`);
out.push('');
out.push('/**');
out.push(' * `27 · Your Starting Point` — the ring gauge and the ELO curve.');
out.push(' *');
out.push(' * 48 tick marks around a 240 x 240 box, a 104pt track at 10pt, and an arc whose');
out.push(' * dash length is the score\'s share of the circumference: the frame\'s own');
out.push(' * `89.7 / 653.5` is 13.73%, and its readout is 412 of 3,000 — 13.73%. The curve');
out.push(' * is 61 samples of a bell peaking at x 172.5, which is 1,500 on a 0…3,000 axis.');
out.push(' */');
out.push(`export const SCORE_RING = ${j({ ticks: score.ticks, trackR: score.trackR, strokeW: score.strokeW, circumference: score.circumference })};`);
out.push(`export const SCORE_CURVE: [number, number][] = ${j(score.curve)};`);
out.push('/** What the frame itself draws, kept so the spec can quote it. */');
out.push(`export const SCORE_SAMPLE = ${j({ score: 412, of: 3000, dash: score.sampleDash, markerX: score.sampleMarkerX })};`);
out.push('');
fs.writeFileSync('src/content/onboardingTail.ts', out.join('\n'));
console.log(`src/content/onboardingTail.ts — cost30 ${cost30.length} (${cost30.filter(Boolean).length} dark), cost365 ${cost365.length} (${cost365.filter(Boolean).length} dark), stars ${age80Stars.length}, bars ${windowBars.length}, ticks ${score.ticks.length}, curve ${score.curve.length}`);
