#!/usr/bin/env node
/**
 * UI FINAL 1 ledger.
 *
 * The ledger is `UI_FINAL_1_LEDGER.md` at the repo root — the run's memory
 * across context resets. It is generated from the split frame indices under
 * `.uifinal1/final/*`, so a frame in the bundle cannot silently drop out of it.
 *
 *   init    — (re)build the ledger, preserving any status/target/note already
 *             recorded for a row that still exists.
 *   set     — update one or more rows: `set <keyGlob> <STATUS> [--target=x] [--note=y]`
 *   status  — print a status tally.
 *
 * Row key is `<bundleSlug>/<frameLabel>`.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const LEDGER = path.join(ROOT, 'UI_FINAL_1_LEDGER.md');
const SPLIT = path.join(ROOT, '.uifinal1', 'final');
const STATUSES = ['NOT_STARTED', 'SPEC_EXTRACTED', 'IMPLEMENTED', 'PASS_1', 'PASS_2', 'PASS_3', 'DONE', 'REFERENCE'];
const SUMMARY_MARK = '**Totals —**';

/** Rewrite the one-line tally under the header so the top of the file is never stale. */
function refresh() {
  const lines = fs.readFileSync(LEDGER, 'utf8').split('\n');
  const counts = {};
  let total = 0;
  for (const line of lines) {
    if (!line.startsWith('| `')) continue;
    const s = line.split('|')[4].trim();
    counts[s] = (counts[s] ?? 0) + 1;
    total++;
  }
  const i = lines.findIndex((l) => l.startsWith(SUMMARY_MARK));
  const text = `${SUMMARY_MARK} ${total} frames. ` + STATUSES.filter((s) => counts[s]).map((s) => `${s}: ${counts[s]}`).join(' · ');
  if (i >= 0) lines[i] = text;
  fs.writeFileSync(LEDGER, lines.join('\n'));
}

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');

function readExisting() {
  const rows = new Map();
  if (!fs.existsSync(LEDGER)) return rows;
  for (const line of fs.readFileSync(LEDGER, 'utf8').split('\n')) {
    if (!line.startsWith('| `')) continue;
    const cells = line.split('|').map((c) => c.trim());
    // | key | frame file | target | status | verified | note |
    const key = cells[1].replace(/^`|`$/g, '');
    rows.set(key, { target: cells[3], status: cells[4], verified: cells[5], note: cells[6] });
  }
  return rows;
}

function bundles() {
  return fs
    .readdirSync(SPLIT)
    .filter((d) => fs.existsSync(path.join(SPLIT, d, '_index.json')))
    .sort();
}

function build() {
  const prev = readExisting();
  const out = [];
  out.push('# UI FINAL 1 — implementation ledger');
  out.push('');
  out.push('Generated by `scripts/uifinal1/ledger.mjs` from the split frame indices in');
  out.push('`.uifinal1/final/`. Every frame in `UI Final 1/` has a row here; a frame cannot');
  out.push('drop out of the run without the row going missing from this file.');
  out.push('');
  out.push('Statuses: `NOT_STARTED` → `SPEC_EXTRACTED` → `IMPLEMENTED` → `PASS_1` → `PASS_2` → `PASS_3` → `DONE`.');
  out.push('`REFERENCE` marks a frame that is documentation of a superseded design rather than a build target');
  out.push('(the reason is always given in the note and in `DECISIONS.md`).');
  out.push('');
  let total = 0;
  const tally = {};
  for (const b of bundles()) {
    const idx = JSON.parse(fs.readFileSync(path.join(SPLIT, b, '_index.json'), 'utf8'));
    out.push(`## ${b}  (${idx.count} frames)`);
    out.push('');
    out.push(`Source: \`${idx.source}\``);
    out.push('');
    out.push('| Key | Frame file | Target app file | Status | Verified | Note |');
    out.push('| --- | --- | --- | --- | --- | --- |');
    for (const f of idx.frames) {
      const key = `${b}/${f.label}`;
      const p = prev.get(key) ?? {};
      const status = STATUSES.includes(p.status) ? p.status : 'NOT_STARTED';
      tally[status] = (tally[status] ?? 0) + 1;
      total++;
      out.push(
        `| \`${esc(key)}\` | ${esc(`.uifinal1/final/${b}/${f.file}`)} | ${esc(p.target ?? '')} | ${status} | ${esc(p.verified ?? '')} | ${esc(p.note ?? '')} |`,
      );
    }
    out.push('');
  }
  const at = out.indexOf('') === -1 ? 0 : out.findIndex((l, i) => i > 8 && l === '');
  out.splice(at + 1, 0, SUMMARY_MARK + ' ', '');
  fs.writeFileSync(LEDGER, out.join('\n'));
  refresh();
  console.log(`ledger: ${total} rows`);
}

function setRows(pattern, status, opts) {
  if (status && !STATUSES.includes(status)) throw new Error('bad status ' + status);
  const lines = fs.readFileSync(LEDGER, 'utf8').split('\n');
  const rx = new RegExp('^' + pattern.replace(/[.+^${}()[\]\\]/g, '\\$&').replace(/\*/g, '.*').replace(/\?/g, '.') + '$');
  let n = 0;
  for (let i = 0; i < lines.length; i++) {
    if (!lines[i].startsWith('| `')) continue;
    const cells = lines[i].split('|');
    const key = cells[1].trim().replace(/^`|`$/g, '');
    if (!rx.test(key)) continue;
    if (status) cells[4] = ` ${status} `;
    if (status) cells[5] = ` ${opts.date} `;
    if (opts.target !== undefined) cells[3] = ` ${esc(opts.target)} `;
    if (opts.note !== undefined) cells[6] = ` ${esc(opts.note)} `;
    lines[i] = cells.join('|');
    n++;
  }
  fs.writeFileSync(LEDGER, lines.join('\n'));
  refresh();
  console.log(`updated ${n} rows matching ${pattern}`);
}

function tally() {
  refresh();
  const counts = {};
  const byBundle = {};
  let bundle = '';
  for (const line of fs.readFileSync(LEDGER, 'utf8').split('\n')) {
    if (line.startsWith('## ')) bundle = line.slice(3).split('  (')[0];
    if (!line.startsWith('| `')) continue;
    const s = line.split('|')[4].trim();
    counts[s] = (counts[s] ?? 0) + 1;
    byBundle[bundle] = byBundle[bundle] ?? {};
    byBundle[bundle][s] = (byBundle[bundle][s] ?? 0) + 1;
  }
  for (const [b, c] of Object.entries(byBundle)) {
    console.log(b.padEnd(34), Object.entries(c).map(([k, v]) => `${k}=${v}`).join(' '));
  }
  console.log('TOTAL'.padEnd(34), Object.entries(counts).map(([k, v]) => `${k}=${v}`).join(' '));
}

const [, , cmd, ...rest] = process.argv;
const opts = { date: new Date().toISOString().slice(0, 10) };
const positional = [];
for (const a of rest) {
  const m = a.match(/^--(target|note|date)=([\s\S]*)$/);
  if (m) opts[m[1]] = m[2];
  else positional.push(a);
}
if (cmd === 'init') build();
else if (cmd === 'set') setRows(positional[0], positional[1], opts);
else if (cmd === 'status') tally();
else {
  console.error('usage: ledger.mjs init | set <keyGlob> <STATUS> [--target=] [--note=] | status');
  process.exit(1);
}
