#!/usr/bin/env node
/**
 * Generate / refresh UI_FINAL_LEDGER.md from the split canvases plus the
 * hand-authored design->app mapping in `map.json`.
 *
 * The ledger is regenerated from the split index every time, so a frame that
 * exists in `UI Final` cannot silently drop out of the ledger. Statuses and
 * notes are read back out of the existing ledger and preserved.
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const LEDGER = path.join(ROOT, 'UI_FINAL_LEDGER.md');
import { mapFor } from './map.mjs';

/** Hand-written per-row overrides, written as work proceeds. */
const OVERRIDE_PATH = path.join(ROOT, 'scripts/uifinal/overrides.json');
const OVERRIDE = fs.existsSync(OVERRIDE_PATH) ? JSON.parse(fs.readFileSync(OVERRIDE_PATH, 'utf8')) : {};

const BUNDLES = [
  { key: 'Email Login', design: 'UI Final/project/Email Login.dc.html', split: '.uifinal/final/Email Login' },
  { key: 'Lessons and Tasks', design: 'UI Final/project/Lessons and Tasks.dc.html', split: '.uifinal/final/Lessons and Tasks' },
  { key: 'Lesson 1 Surviving the Night', design: 'UI Final/project/Lesson 1 Surviving the Night.dc.html', split: '.uifinal/final/Lesson 1 Surviving the Night' },
  { key: 'VICI (previous)', design: 'UI Final/project/VICI (previous).dc.html', split: '.uifinal/final/VICI (previous)' },
  { key: 'vici-prev', design: 'UI Final/project/vici-prev.dc.html', split: '.uifinal/final/vici-prev' },
  { key: 'exports/Journey Campaign', design: 'UI Final/project/exports/Journey Campaign.html', split: '.uifinal/final/exports-Journey Campaign' },
  { key: 'exports/Lesson Detail', design: 'UI Final/project/exports/Lesson Detail.html', split: '.uifinal/final/exports-Lesson Detail' },
  { key: 'exports/Lesson Parts', design: 'UI Final/project/exports/Lesson Parts.html', split: '.uifinal/final/exports-Lesson Parts' },
];

// Preserve status/date/note from the current ledger, keyed by "bundle::label".
const existing = new Map();
if (fs.existsSync(LEDGER)) {
  for (const line of fs.readFileSync(LEDGER, 'utf8').split('\n')) {
    const m = line.match(/^\| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \| ([^|]*) \|$/);
    if (!m) continue;
    const [, bundle, label, target, status, verified, note] = m.map((s) => s.trim());
    if (bundle === 'Bundle' || bundle.startsWith('---')) continue;
    existing.set(`${bundle}::${label}`, { target, status, verified, note });
  }
}

const rows = [];
for (const b of BUNDLES) {
  const idx = JSON.parse(fs.readFileSync(path.join(b.split, '_index.json'), 'utf8'));
  const notesPath = path.join(b.split, '_notes.json');
  const notes = fs.existsSync(notesPath)
    ? new Map(JSON.parse(fs.readFileSync(notesPath, 'utf8')).map((n) => [n.label, n.note]))
    : new Map();
  for (const f of idx.frames) {
    const key = `${b.key}::${f.label}`;
    const prior = existing.get(key);
    const mapped = mapFor(b.key, f.label);
    rows.push({
      bundle: b.key,
      label: f.label,
      frame: `${b.split}/${f.file}`,
      // target + note come from map.mjs (the source of truth) unless a
      // hand-written override exists; only progress is read back off the ledger.
      target: OVERRIDE[key]?.target ?? mapped.target ?? '—',
      status: prior?.status ?? 'NOT_STARTED',
      verified: prior?.verified ?? '—',
      note: OVERRIDE[key]?.note ?? (mapped.note !== '—' ? mapped.note : notes.get(f.label) ?? '—'),
    });
  }
}

const esc = (s) => String(s).replace(/\|/g, '\\|');
const counts = rows.reduce((a, r) => ((a[r.status] = (a[r.status] ?? 0) + 1), a), {});

const out = [];
out.push('# UI Final — implementation ledger');
out.push('');
out.push('Generated by `node scripts/uifinal/ledger.mjs`. Every `data-screen-label` frame in');
out.push('every file under `UI Final/` gets exactly one row. Regenerating never drops a row:');
out.push('statuses and notes are read back out of this file and re-applied.');
out.push('');
out.push('Statuses: `NOT_STARTED` → `SPEC_EXTRACTED` → `IMPLEMENTED` → `PASS_1` → `PASS_2` → `PASS_3` → `DONE`.');
out.push('');
out.push(`**${rows.length} rows.** ` + Object.entries(counts).map(([k, v]) => `${k}: ${v}`).join(' · '));
out.push('');
out.push('| Bundle | Screen | Target app file | Status | Verified | Note |');
out.push('| --- | --- | --- | --- | --- | --- |');
for (const r of rows) out.push(`| ${esc(r.bundle)} | ${esc(r.label)} | ${esc(r.target)} | ${r.status} | ${r.verified} | ${esc(r.note)} |`);
out.push('');
fs.writeFileSync(LEDGER, out.join('\n'));
console.log(`ledger: ${rows.length} rows`, counts);
