/* GROUP slip — exercise 98C's controls: chips, wheel taps, the future clamp, Change + the day sheet, back. */
const out = { push: (s) => console.error("EX " + s) };
const row = () => { const m = __txt().match(/(Tonight|Today|Last night|Yesterday)?,? ?(\w{3} \w{3} \d+)/); return m ? m[0] : '?'; };
const checked = () => [...document.querySelectorAll('[role="radio"][aria-checked="true"]')].map((e) => e.textContent.trim());
const vals = () => [...document.querySelectorAll('[aria-valuetext]')].map((e) => e.getAttribute('aria-valuetext')).join(' ');
await tap('Log the slip'); await tap('Continue');
out.push('start: ' + vals() + ' | ' + row() + ' | on=' + checked());
await tap('Hour 10', { wait: 900 });
out.push('hour10: ' + vals() + ' | ' + row() + ' | on=' + JSON.stringify(checked()));
await tap('Minute 42', { wait: 900 });
out.push('min42: ' + vals() + ' | ' + row());
await tap('Hour 12', { wait: 900 }); await tap('Hour 1', { wait: 900 });
out.push('future try (hour+): ' + vals() + ' | ' + row());
await tap('Yesterday');
out.push('yesterday chip: ' + vals() + ' | ' + row() + ' | on=' + checked());
await tap('Earlier today');
out.push('earlier chip: ' + vals() + ' | ' + row() + ' | on=' + checked());
await tap('Just now');
await tap('Change', { wait: 700 });
const opts = [...document.querySelectorAll('[role="radio"]')].map((e) => e.textContent.trim() + (e.getAttribute('aria-checked') === 'true' ? '*' : '')).filter((t) => /\w{3} \w{3} \d/.test(t));
out.push('sheet: ' + opts.join(' / '));
await tap('Sun Jul 20', { wait: 900 });
out.push('picked Sun: ' + vals() + ' | ' + row() + ' | on=' + JSON.stringify(checked()) + ' | sheetOpen=' + __txt().includes('Mon Jul 21'));
await tap('Back');
out.push('back -> ' + __txt().slice(0, 30));
await tap('Continue'); await tap('Continue');
out.push('again: ' + __txt().slice(0, 40));
await tap('Back'); await tap('Back');
out.push('back x2 -> ' + __txt().slice(0, 30));
return "done";
