#!/usr/bin/env node
/**
 * GROUP today — `scripts/overhaul/shot.mjs app` with the canvas's own account
 * seeded before the app boots.
 *
 * `/today` and `/score` are opened directly, so nothing has signed a mock user
 * in and `.overhaul/reseed.js` has no `tideline.mock.userdata.*` key to rewrite.
 * Seeding after the fact needs a reload, and a reload destroys the execution
 * context `shot.mjs` drives from — so the account goes in as an init script,
 * which lands before the first paint.
 *
 * The account itself is regenerated by `scripts/uifinal1/seed.mjs` on every
 * capture rather than read from `.overhaul/seed.json`: that file is a snapshot
 * taken on the previous run's "today", and the generator dates everything
 * relative to `now`, so the snapshot now reads Day 54 where the canvas draws
 * Day 41.
 *
 *   node .overhaul/todayshot.mjs "/today" out.png --sig=name [--do='…'] [--wait=ms]
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright-core';

const PROBE = fs.readFileSync('.overhaul/probe.js', 'utf8');
const DRIVE = fs.readFileSync('.overhaul/drive.js', 'utf8');
const seed = JSON.parse(execFileSync('node', ['scripts/uifinal1/seed.mjs'], { encoding: 'utf8', maxBuffer: 64 << 20 }));

/**
 * `21 · Today` prints "▲ 18" beside the number, which is `buildScore`'s delta:
 * 4 for the clean day, 2 for this morning's check-in and 2 per urge ridden
 * today — so the frame's own account rode six out today. The generator spreads
 * its twenty-four urges evenly and lands one on today, giving 8. Six of them
 * are moved onto today here, which leaves every total the score is built from
 * untouched (same count, same types) and lets the arrow row be compared at the
 * width the canvas draws it.
 */
function sixUrgesToday(seed) {
  const midnight = new Date().setHours(0, 0, 0, 0);
  const ridden = seed.events.filter((e) => e.type === 'urge_rode_out');
  ridden.slice(0, 6).forEach((e, i) => { e.createdAt = midnight + (14 + i) * 3600e3; });
}

const UID = 'today-seed-user';
sixUrgesToday(seed);

/**
 * `--day=N` moves the account's opening back so `Today` counts N days.
 *
 * `21 · Today — p2` draws the task card's fallback register — the phone in the
 * drawer, the crescent, "Today’s task" — which `today.tsx` reaches only past
 * the 84-lesson curriculum, because before then the day's own lesson takes the
 * card and that is the sibling frame `21 · Today — task`. The two states cannot
 * both belong to one account, so p2 is captured at day 86.
 */
if (process.argv.some((a) => a.startsWith('--day='))) {
  const n = Number(process.argv.find((a) => a.startsWith('--day=')).slice(6));
  seed.user.createdAt = new Date().setHours(0, 0, 0, 0) - (n - 1) * 86400000;
}
seed.user.clerkUserId = UID;
seed.lifeMap.userId = UID;
for (const e of seed.events) e.userId = UID;
for (const k of Object.keys(seed.checkins)) seed.checkins[k].userId = UID;
for (const k of Object.keys(seed.progress)) seed.progress[k].userId = UID;
for (const j of seed.journalEntries) j.userId = UID;

const SEED = `
localStorage.setItem('tideline.mock.users', ${JSON.stringify(JSON.stringify({ 'seed@vici.app': { userId: UID, email: 'seed@vici.app', password: 'x', displayName: seed.user.displayName } }))});
localStorage.setItem('tideline.session.userId', ${JSON.stringify(UID)});
localStorage.setItem('tideline.mock.userdata.' + ${JSON.stringify(UID)}, ${JSON.stringify(JSON.stringify(seed))});
`;

const argv = process.argv.slice(2);
const flags = Object.fromEntries(argv.filter((a) => a.startsWith('--')).map((a) => { const i = a.indexOf('='); return i < 0 ? [a.slice(2), true] : [a.slice(2, i), a.slice(i + 1)]; }));
const [route, out] = argv.filter((a) => !a.startsWith('--'));

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 2 });
await ctx.addInitScript(`try { ${SEED} } catch (e) { console.error('seed: ' + e.message); }`);
const page = await ctx.newPage();
page.on('console', (m) => { if (m.type() === 'error') console.error('[console] ' + m.text()); });

await page.goto('http://localhost:8096' + (route.startsWith('/') ? route : '/' + route), { waitUntil: 'networkidle' });
await page.evaluate(DRIVE);
if (flags.do) { const r = await page.evaluate(`(async () => { ${flags.do} })()`); if (r) console.log('do ->', JSON.stringify(r).slice(0, 400)); }
if (flags.script) { const r = await page.evaluate(`(async () => { ${fs.readFileSync(flags.script, 'utf8')} })()`); if (r) console.log('script ->', JSON.stringify(r).slice(0, 400)); }
await page.waitForTimeout(Number(flags.wait ?? 1200));
if (flags.sig) {
  await page.evaluate(PROBE);
  const rows = await page.evaluate((n) => window.__sigRows(n), flags.sig);
  fs.mkdirSync('.overhaul/sig', { recursive: true });
  fs.writeFileSync('.overhaul/sig/' + String(flags.sig).replace(/[^A-Za-z0-9._-]/g, '_') + '.txt', rows);
  console.log(rows.split('\n').length + ' rows -> ' + flags.sig);
}
if (out && out !== '-') {
  fs.mkdirSync(path.dirname(out), { recursive: true });
  await page.screenshot({ path: out });
  console.log('shot -> ' + out);
}
await browser.close();
