const L = [];
const has = (s) => __txt().includes(s);
const ok = (name, v) => L.push((v ? 'PASS ' : 'FAIL ') + name);
const checked = () => [...document.querySelectorAll('[aria-checked="true"],[aria-selected="true"]')].map((e) => (e.getAttribute('aria-label') || e.textContent.trim()));
const ctl = (label) => __btns().find((b) => b.getAttribute('aria-label') === label || b.textContent.trim() === label);
ok('cover copy', has('Night check-in.') && has('Day 13, about two minutes'));
await tap('Begin'); await __sleep(700);
ok('mood step', has('How was today?') && has('Mixed') && has('Some of both'));
await tap('Back'); await __sleep(500);
ok('back -> cover', has('Night check-in.'));
await tap('Begin'); await __sleep(700);
for (const [w, l] of [['Heavy', 'A hard one'], ['Low', 'It took something'], ['Good', 'More right than wrong'], ['Bright', 'One to keep']]) { await tap(w); await __sleep(200); ok('mood ' + w, has(l)); }
await tap('Continue'); await __sleep(700);
ok('emotions step', has('What did today feel like?') && has('Select all that apply.'));
ok('none checked', checked().length === 0);
const nx = ctl('Next'); ok('next disabled', nx && nx.getAttribute('aria-disabled') === 'true');
__fire(nx); await __sleep(400); ok('next blocked', has('What did today feel like?'));
await tap('Tense'); await __sleep(200); await tap('Calm'); await __sleep(200); await tap('Tired'); await __sleep(200); await tap('Tense'); await __sleep(200);
L.push('emotions checked ' + JSON.stringify(checked()));
await tap('Next'); await __sleep(700);
ok('reasons step', has('What caused the feeling?') && has('Health') && !has('Health / wellbeing'));
ok('reasons none checked', checked().length === 0);
await tap('Back'); await __sleep(500);
ok('back to emotions keeps picks', JSON.stringify(checked()) );
L.push('emotions after back ' + JSON.stringify(checked()));
await tap('Next'); await __sleep(700);
await tap('Health'); await __sleep(200); await tap('Money'); await __sleep(200);
L.push('reasons checked ' + JSON.stringify(checked()));
await tap('Next'); await __sleep(800);
ok('reflection step', has('Anything worth keeping?') && has('Optional'));
const ta = document.querySelector('textarea');
L.push('reflection placeholder ' + (ta && ta.placeholder) + ' color ' + (ta && getComputedStyle(ta, '::placeholder').color));
{ const d = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(ta), 'value'); d.set.call(ta, 'A good call with Sam.'); ta.dispatchEvent(new Event('input', { bubbles: true })); }
await __sleep(300);
await tap('Continue'); await __sleep(900);
ok('record step', has('Today’s record.') && has('Pledge kept') && has('One urge surfed') && has('0 slips') && has('Part IV finished') && has('Add to the record'));
await tap('Back'); await __sleep(600);
const ta3 = document.querySelector('textarea');
ok('back to reflection keeps text', ta3 && ta3.value === 'A good call with Sam.');
await tap('Continue'); await __sleep(900);
await tap('Continue'); await __sleep(900);
ok('action step', has('Tonight’s action') && has('Done') && has('Skip tonight'));
L.push('action text ' + __txt().slice(0, 160));
await tap('Skip tonight'); await __sleep(900);
ok('closed', has('Day 13, closed.') && has('See you in the morning.'));
ok('closed no back', !ctl('Back'));
await tap('Done'); await __sleep(2200);
const key = Object.keys(localStorage).find((k) => k.startsWith('tideline.mock.userdata.'));
const data = JSON.parse(localStorage.getItem(key));
const d2 = (ms) => { const d = new Date(ms); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
L.push('url ' + location.pathname);
L.push('today row ' + JSON.stringify(data.checkins[d2(Date.now())]));
L.push('tomorrow row ' + JSON.stringify(data.checkins[d2(Date.now() + 86400000)]));
L.push('reflections ' + JSON.stringify((data.journalEntries || []).filter((j) => j.tag === 'Reflection').map((j) => [j.title, j.body])));
console.error('LOG ' + JSON.stringify(L));
return L.filter((x) => x.startsWith('FAIL')).length + ' fails';
