const L = [];
const has = (s) => __txt().includes(s);
const ok = (name, v) => L.push((v ? 'PASS ' : 'FAIL ') + name);
const checked = () => [...document.querySelectorAll('[aria-checked="true"],[aria-selected="true"]')].map((e) => (e.getAttribute('aria-label') || e.textContent.trim()));
L.push('step0: ' + __txt().slice(0, 120) + ' checked ' + JSON.stringify(checked()));
await tap('Continue'); await __sleep(700);
L.push('step1: ' + __txt().slice(0, 60) + ' checked ' + JSON.stringify(checked()));
await tap('Next'); await __sleep(700);
L.push('step2: ' + __txt().slice(0, 60) + ' checked ' + JSON.stringify(checked()));
ok('Health / wellbeing shown as Health', checked().includes('Health'));
await tap('Back'); await __sleep(500);
ok('back to step1', has('What did today feel like?'));
await tap('Next'); await __sleep(600);
await tap('Self-image'); await __sleep(200);
await tap('Log it'); await __sleep(2200);
const key = Object.keys(localStorage).find((k) => k.startsWith('tideline.mock.userdata.'));
const data = JSON.parse(localStorage.getItem(key));
const d2 = (ms) => { const d = new Date(ms); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
L.push('url ' + location.pathname);
L.push('today row ' + JSON.stringify(data.checkins[d2(Date.now())]));
console.error('LOG ' + JSON.stringify(L));
return 'x';
