const L = [];
const has = (s) => __txt().includes(s);
const ok = (name, v) => L.push((v ? 'PASS ' : 'FAIL ') + name);
await tap('Begin'); await __sleep(700);
await tap('Continue'); await __sleep(700);
await tap('Proud'); await __sleep(200);
await tap('Next'); await __sleep(700);
await tap('Family'); await __sleep(200);
await tap('Next'); await __sleep(800);
await tap('Continue'); await __sleep(900);
ok('record', has('Today’s record.'));
await tap('Add to the record'); await __sleep(2500);
L.push('after add: ' + location.pathname + ' :: ' + __txt().slice(0, 100));
history.back(); await __sleep(2500);
L.push('after back: ' + location.pathname + ' :: ' + __txt().slice(0, 80));
ok('back on record step', has('Today’s record.'));
await tap('Continue'); await __sleep(900);
await tap('Done'); await __sleep(900);
ok('closed', has('Day 13, closed.'));
await tap('Close'); await __sleep(2200);
const key = Object.keys(localStorage).find((k) => k.startsWith('tideline.mock.userdata.'));
const data = JSON.parse(localStorage.getItem(key));
const d2 = (ms) => { const d = new Date(ms); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
L.push('url ' + location.pathname);
L.push('today row ' + JSON.stringify(data.checkins[d2(Date.now())]));
L.push('tomorrow row ' + JSON.stringify(data.checkins[d2(Date.now() + 86400000)]));
L.push('reflections ' + JSON.stringify((data.journalEntries || []).filter((j) => j.tag === 'Reflection').length));
console.error('LOG ' + JSON.stringify(L));
return L.filter((x) => x.startsWith('FAIL')).length + ' fails';
