const L = [];
const has = (s) => __txt().includes(s);
const ok = (name, v) => L.push((v ? 'PASS ' : 'FAIL ') + name);
const checked = () => [...document.querySelectorAll('[aria-checked="true"],[aria-selected="true"]')].map((e) => (e.getAttribute('aria-label') || e.textContent.trim()));
const ctl = (label) => __btns().find((b) => b.getAttribute('aria-label') === label || b.textContent.trim() === label);
ok('cover copy', has('Morning check-in.') && has('Day 13, about two minutes'));
ok('cover has no Back', !ctl('Back'));
await tap('Begin'); await __sleep(600);
ok('task step', has('Did you complete this task?') && has('Write down each trigger the moment you notice it.'));
ok('nothing checked on arrival', checked().length === 0);
const nx = ctl('Next');
ok('Next aria-disabled', nx && (nx.getAttribute('aria-disabled') === 'true'));
__fire(nx); await __sleep(500);
ok('Next before choice stays', has('Did you complete this task?'));
await tap('Yes'); await __sleep(250);
ok('Yes checked', JSON.stringify(checked()));
await tap('Not yet'); await __sleep(250);
L.push('checked after Not yet: ' + JSON.stringify(checked()));
await tap('Next'); await __sleep(600);
ok('ledger', has('Yesterday’s record.'));
L.push('ledger text: ' + __txt().slice(0, 200));
await tap('Back'); await __sleep(500);
ok('back to task, Not yet kept', has('Did you complete this task?') && checked().includes('Not yet'));
await tap('Back'); await __sleep(500);
ok('back from task to cover', has('Morning check-in.'));
await tap('Begin'); await __sleep(600);
ok('re-begin keeps Not yet', checked().includes('Not yet'));
await tap('Next'); await __sleep(600);
await tap('Continue'); await __sleep(600);
ok('feeling default Steady', has('How are you feeling?') && has('Steady') && has('On level ground'));
L.push('feeling checked: ' + JSON.stringify(checked()));
for (const [w, l] of [['Rough', 'Start slow'], ['Low', 'Not much in reserve'], ['Good', 'Steady and clear'], ['Great', 'Ready for it']]) { await tap(w); await __sleep(200); ok('feeling ' + w, has(l)); }
await tap('Continue'); await __sleep(600);
ok('energy default Low', has('Where’s your energy?') && has('Still warming up'));
L.push('energy checked: ' + JSON.stringify(checked()));
for (const [w, l] of [['Empty', 'Ask little of yourself'], ['Enough', 'Steady pace'], ['Good', 'Room to push'], ['Full', 'Use it']]) { await tap(w); await __sleep(200); ok('energy ' + w, has(l)); }
await tap('Back'); await __sleep(500);
ok('back to feeling keeps Great', has('Ready for it'));
await tap('Continue'); await __sleep(500);
ok('energy keeps Full', has('Use it'));
await tap('Continue'); await __sleep(700);
ok('pledge unsigned', has('Re-sign your pledge.') && has('Sign here') && has('Sign for today') && has('The mornings are mine again.'));
L.push('pledge ctl labels: ' + JSON.stringify(__btns().map((b) => b.getAttribute('aria-label') || b.textContent.trim()).slice(0, 12)));
await tap('Sign for today'); await __sleep(400);
ok('sign via pill', has('Jerry') && has('Confirm'));
await tap('Change the pledge'); await __sleep(800);
const ta = document.querySelector('textarea');
ok('sheet open, field prefilled', has('One promise you can keep every day.') && ta && ta.value === 'The mornings are mine again.');
{ const d = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(ta), 'value'); d.set.call(ta, 'Abandoned edit'); ta.dispatchEvent(new Event('input', { bubbles: true })); }
await __sleep(200);
// scrim: whatever is painted at the very top (y 30) should dismiss
let el = document.elementFromPoint(196, 30); let p = el; let path = [];
while (p) { path.push((p.getAttribute && (p.getAttribute('role') || '') + ':' + (p.getAttribute('aria-label') || '')) || ''); p = p.parentElement; }
L.push('at 196,30: ' + path.slice(0, 5).join(' < '));
await tapAt(196, 30); await __sleep(700);
ok('scrim closes sheet', !has('One promise you can keep every day.'));
ok('scrim keeps signed + old pledge', has('Jerry') && has('The mornings are mine again.'));
await tap('Change the pledge'); await __sleep(800);
const ta2 = document.querySelector('textarea');
ok('reopen shows standing pledge not abandoned edit', ta2 && ta2.value === 'The mornings are mine again.');
{ const d = Object.getOwnPropertyDescriptor(Object.getPrototypeOf(ta2), 'value'); d.set.call(ta2, 'Phone stays out of the bedroom'); ta2.dispatchEvent(new Event('input', { bubbles: true })); }
await __sleep(300);
await tap('Sign the new pledge'); await __sleep(700);
ok('new pledge on card, unsigned', has('Phone stays out of the bedroom') && has('Sign here') && has('Sign for today'));
await tap('Sign here'); await __sleep(400);
ok('line signs', has('Jerry') && has('Confirm'));
L.push('signed line labels: ' + JSON.stringify(__btns().map((b) => b.getAttribute('aria-label')).filter(Boolean)));
await tap('Confirm'); await __sleep(700);
ok('done step', has('Day 13, underway.') && has('Pledge re-signed on Day 13'));
ok('done has no Back', !ctl('Back'));
ok('done has Close', !!ctl('Close'));
await tap('Close'); await __sleep(2000);
const key = Object.keys(localStorage).find((k) => k.startsWith('tideline.mock.userdata.'));
const data = JSON.parse(localStorage.getItem(key));
const d2 = (ms) => { const d = new Date(ms); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
L.push('url ' + location.pathname);
L.push('today row ' + JSON.stringify(data.checkins[d2(Date.now())]));
L.push('yest row ' + JSON.stringify(data.checkins[d2(Date.now() - 86400000)]));
L.push('pledges ' + JSON.stringify((data.journalEntries || []).filter((j) => j.tag === 'Pledge').map((j) => [j.title, j.body])));
console.error('LOG ' + JSON.stringify(L, null, 0));
return L.filter((x) => x.startsWith('FAIL')).length + ' fails';
