/**
 * `38 · A Letter From Week XII` — the letter, word for word off the frame.
 *
 * GENERATED by `scripts/uifinal1/gen-letter.mjs`. The previous bundle built this
 * letter out of the answers; this one writes it. Only the name is his.
 */
export const WEEK_XII_LETTER: string[] = [
  "I’m writing this at the end of week XII.",
  "I remember where you are right now. You want this to be the time it finally changes, but part of you is already wondering how long you’ll last. I was thinking the same thing.",
  "So here is the part I wish you knew: you do not need twelve perfect weeks. You need to stop turning one bad night into a reason to quit.",
  "There were nights when I wanted to watch badly. Some days the only thing I did right was get through the evening. That still counted.",
  "And there were bad days. What changed was what happened after them. I stopped saying “I’ve ruined it now, so what is the point?” I came back the next morning. I logged what happened. I carried on.",
  "At the start, porn still felt like the quickest relief when I was bored, stressed, lonely, or fed up. That did not disappear in a week. But every time I waited one out, left the room, or used the SOS instead, I learned the same thing: the urge ends whether you obey it or not.",
  "After a while, that changes you. You stop being scared of an urge because you have seen enough of them come and go. You stop treating every difficult night like an emergency. You start trusting yourself again.",
  "The biggest difference is not a streak. It is waking up without the feeling that you gave another night away. It is having more time and attention for the things you said you wanted back.",
  "I am not going to tell you everything is fixed here. It is not. I still have bad days. I still get urges. They are just not running the whole show anymore.",
  "If you are reading this on day 0, do not try to get to week XII tonight. Get through tonight. Tomorrow, come back. If you slip, do not disappear for a week because you are embarrassed. Come back the next morning.",
  "That is how you make it out: you keep coming back long enough for things to change.",
  "Hard nights end. Urges end. Bad days end. None of them has to be the day you give up. Do not quit on yourself halfway through. I’ll see you at week XII.",
];
