const out = {};
const vis = () => [...document.querySelectorAll('[role="heading"]')].filter(e=>{const r=e.getBoundingClientRect();return r.left>-1&&r.right<innerWidth+1&&r.width>0}).map(e=>e.textContent);
await __sleep(500);
await tap('A week · board'); await __sleep(1800);
out.week1 = vis();
const pager = [...document.querySelectorAll('*')].find(e => /(auto|scroll)/.test(getComputedStyle(e).overflowX) && e.scrollWidth > e.clientWidth * 5);
pager.scrollLeft = 3 * innerWidth; pager.dispatchEvent(new Event('scroll')); await __sleep(900);
out.swiped = vis();
await tap('A week · board'); await __sleep(1800);
out.again = { path: location.pathname + location.search, h: vis() };
return out;
