const log = [];
const url = () => location.pathname + location.search;
const step = async (name, fn, wait = 1300) => { try { await fn(); await __sleep(wait); log.push([name, url(), __txt().slice(0, 140)]); } catch (e) { log.push([name, 'ERR ' + e.message.slice(0, 200)]); } };
await __sleep(800);
log.push(['start', url(), __txt().slice(0, 160)]);
await step('tap Breakwater cell', () => tap('Breakwater. Tier I, ×1'));
await step('tap track', () => tap('See every tier'), 1600);
await step('ladder Back to medallions', () => tap('Back to medallions'), 1500);
await step('album back chevron?', async () => { log.push(['canGoBack-check', history.length]); });
await step('Still to earn', () => tap('Still to earn'), 600);
await step('tap Archive', () => tap('Archive. 9 of 10 entries'));
await step('archive track', () => tap('See every tier'), 1500);
await step('archive ladder back chevron', () => tap('Back'), 1300);
await step('archive board back to medallions (unearned cta)', () => tap('Back to medallions'), 1300);
await step('tap Return', () => tap('Return. After 7 days away'));
await step('return caps -> once', () => tap('Not yet. Every one-off'), 1500);
await step('once back', () => tap('Back'), 1300);
await step('return board back', () => tap('Back'), 1300);
await step('Earned', () => tap('Earned'), 600);
await step('tap Veni', () => tap('Veni. Jun 9'));
await step('veni caps -> once', () => tap('Jun 9. Every one-off'), 1500);
await step('once back', () => tap('Back'), 1300);
await step('veni Share this', () => tap('Share this'), 800);
await step('veni nav share', () => tap('Share'), 800);
await step('veni back', () => tap('Back'), 1300);
await step('album back', () => tap('Back'), 1300);
console.error("LOG " + JSON.stringify(log)); return 1;
