const log = [];
const url = () => location.pathname + location.search;
const ls = (k) => localStorage.getItem(k);
const step = async (name, fn, wait = 1300) => { try { await fn(); await __sleep(wait); log.push([name, url(), __txt().slice(0, 200)]); } catch (e) { log.push([name, 'ERR ' + e.message.slice(0, 200)]); } };
await __sleep(800);
log.push(['start', url(), __txt().slice(0, 200)]);
await step('Restore (nav)', () => tap('Restore'), 1800);
await step('Terms · Restore', () => tap('Terms · Restore'), 1800);
await step('Unlock my year', () => tap('Unlock my year'), 2200);
log.push(['after unlock', 'seen=' + ls('tideline.post.yearlydrop.seen')]);
await step('See the receipt', () => tap('See the receipt'), 2000);
console.error("LOG " + JSON.stringify(log)); return 1;
